### ISSUE TITLE
规则引擎-模型导入导出

### ISSUE THREAD

**Issue by zhou-hao** [jetlinks/jetlinks-platform#16]
* [x] 规则引擎模型支持导入导出
* [x] 规则模型支持复制
* [x] 规则实例支持转为模型

**Comment by bestfeng1020** [comment]
![image](https://user-images.githubusercontent.com/31398465/68298768-2c54a400-00d5-11ea-9b83-be60fce49636.png)
yi'wan'c已完成

**Comment by bestfeng1020** [comment]
已完成![image](https://user-images.githubusercontent.com/31398465/68298775-324a8500-00d5-11ea-93ac-7bbacbb2cfba.png)

**Comment by bestfeng1020** [comment]
已完成。
![image](https://user-images.githubusercontent.com/31398465/68298801-455d5500-00d5-11ea-9aad-d4a852931e67.png)

**Comment by bestfeng1020** [comment]
完成模型复制、实例转换模型功能
