### ISSUE TITLE
设备管理功能

### ISSUE THREAD

**Issue by zhou-hao** [jetlinks/jetlinks-platform#2]
* [ ] 设备型号
    * [x] 设备型号管理
        * [x]  新增
        * [x]  批量导入
        * [x] 元数据基本配置(属性,功能,事件)
    * [ ] 设备实例
        * [x] 新增
        * [x] 批量导入
        * [x] 设备状态(设备属性,事件)
        * [ ] ~设备调试~ 延期

**Comment by gyf520** [comment]
设备型号现目前做的是单个导出导入,导出的文件为.json文件
