### ISSUE TITLE
设备管理-增加根据设备元数据的数据类型渲染表单页面

### ISSUE THREAD

**Issue by zhou-hao** [jetlinks/jetlinks-platform#20]
根据metadata中的DataType渲染表单组件
* [x] StringType  length大于256的为多行文本,构造为单行文本
* [x] NumberType 根据配置的最大值最小值,步长 生成数字输入框
* [x] BooleanType 单选 根据TrueText 和TrueValue渲染对应的文本和值
* [x] DateType 根据配置的日期格式渲染日期选择框
* [x] EnumType 下拉选择框
* [ ] ObjectType 嵌套表单
* [ ] ArrayType 表格

**Comment by gyf520** [comment]
StringType length大于256的暂时还没做,2019-11-14优化完成

**Comment by gyf520** [comment]
NumberType 分为:int,float,double 都是用的mini-spinner
