### ISSUE TITLE
查询设备日志错误

### ISSUE THREAD

**Issue by zhou-hao** [jetlinks/jetlinks-platform#23]
![3811573186137_ pic_hd](https://user-images.githubusercontent.com/7791838/68450492-3afea080-0226-11ea-9dff-83668908a527.jpg)

**Comment by bestfeng1020** [comment]
已解决，对方es数据库服务版本和客户端版本不一致。

**Comment by bestfeng1020** [comment]
修改es每次查询都会去验证index是否存在的问题
