### ISSUE TITLE
设备管理-设备实例界面bug

### ISSUE THREAD

**Issue by zhou-hao** [jetlinks/jetlinks-platform#25]
* [x] 无法查看属性操作日志
* [x] 查看页面高度问题，分辨率过低时可能导致页面挤出整个屏幕
* [x] 查看设备状态时,  设备属性和事件顺序混乱

**Comment by bestfeng1020** [comment]
已完成。
![image](https://user-images.githubusercontent.com/31398465/68748140-daf96700-0636-11ea-9d2d-1360f05b1847.png)
