### ISSUE TITLE
数据库

### ISSUE THREAD

**Issue by wuhansoft** [jetlinks/jetlinks-platform#28]
数据库文件在哪里？或者怎么建立数据库？

**Comment by zhou-hao** [comment]
自动建

**Comment by wuhansoft** [comment]
io.r2dbc.postgresql.ExceptionFactory$PostgresqlNonTransientResourceException: [3D000] database "jetlinks" does not exist
这个怎么处理？

**Comment by wuhansoft** [comment]
运行后看不到菜单项，是空的
