### ISSUE TITLE
使用mvn spring-boot:run启动，出现错误，请问如何解决？

### ISSUE THREAD

**Issue by inprise1980** [jetlinks/jetlinks-platform#30]
使用mvn spring-boot:run启动，出现如下错误
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.0:prepare-agent (default) @ jetlinks-platform ---
[INFO] argLine set to -javaagent:/home/hadoop/.m2/repository/org/jacoco/org.jacoco.agent/0.8.0/org.jacoco.agent-0.8.0-runtime.jar=destfile=/home/hadoop/jetlinks-platform-master/target/jacoco.exec
[INFO]
[INFO] --- gmavenplus-plugin:1.6.1:addTestSources (default) @ jetlinks-platform ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jetlinks-platform ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ jetlinks-platform ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 89 source files to /home/hadoop/jetlinks-platform-master/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/hadoop/jetlinks-platform-master/src/main/java/org/jetlinks/platform/configuration/JetLinksConfiguration.java:[24,38] 找不到符号
  符号:   类 JetLinksMQTTDeviceMessageCodec
  位置: 程序包 org.jetlinks.supports.official
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.376 s
[INFO] Finished at: 2019-12-31T10:38:10+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project jetlinks-platform: Compilation failure
[ERROR] /home/hadoop/jetlinks-platform-master/src/main/java/org/jetlinks/platform/configuration/JetLinksConfiguration.java:[24,38] 找不到符号
[ERROR]   符号:   类 JetLinksMQTTDeviceMessageCodec
[ERROR]   位置: 程序包 org.jetlinks.supports.official
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by zhou-hao** [comment]
新版本还在开发，暂时没有同步到这里。

**Comment by inprise1980** [comment]
新版本大概何时能发布？是否有初步的时间，谢谢。

**Comment by zhou-hao** [comment]
@inprise1980 预计春节前后会有一个版本。
